steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/mlpt-cloudteam-migration/hict-team',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mlpt-cloudteam-migration/hict-team']

images:
  - 'gcr.io/mlpt-cloudteam-migration/hict-team'
